TARGET?=

CC ?= g++
##compiler inlcude flags
IFLAGS = -std=c++17

#compiler optization flags
OFLAGS = -Os -fopenmp

#warning flags
WFLAGS = -Wall

#-D flags
DFLAGS = 

#other compiler flags
CFLAGS ?=

#####################################
INC = include 

LDFLAGS = -fopenmp -lpthread -lm -fPIC -shared
BIN = bin
